# Generated by Django 5.1.7 on 2026-01-19 21:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost_per_bag',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), help_text='Cost per bag/case', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='item',
            name='units_per_bag',
            field=models.IntegerField(default=1, help_text='Number of units in one bag/case', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost_price',
            field=models.DecimalField(decimal_places=4, help_text='Auto-calculated: cost per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='item',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sell price (set via different logic)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
