# Generated by Django 5.1.7 on 2026-01-19 21:40

from django.db import migrations
from decimal import Decimal


def populate_cost_per_bag(apps, schema_editor):
    """Populate cost_per_bag and units_per_bag from existing cost_price values"""
    Item = apps.get_model('core', 'Item')
    
    for item in Item.objects.all():
        # For existing items, assume cost_per_bag = cost_price and units_per_bag = 1
        # This preserves the existing cost_price value
        if item.cost_per_bag == Decimal('0.01'):  # Only update if still at default
            item.cost_per_bag = item.cost_price
            item.units_per_bag = 1
            item.save()


def reverse_populate_cost_per_bag(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_cost_per_bag_fields'),
    ]

    operations = [
        migrations.RunPython(populate_cost_per_bag, reverse_populate_cost_per_bag),
    ]
