# Generated by Django 5.1.7 on 2026-01-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_cost_per_bag_from_existing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='pickup_spot',
            field=models.CharField(blank=True, help_text='Pickup location/spot', max_length=200, null=True),
        ),
    ]
