# Generated by Django 5.1.7 on 2026-01-20 05:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_customer_email_customer_pickup_spot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('account_type', models.CharField(blank=True, help_text='e.g., Savings, Chequing', max_length=50)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('additional_info', models.TextField(blank=True, help_text='Additional payment instructions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Banking Info',
                'ordering': ['bank_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('pickup_spot', models.CharField(help_text='Pickup location', max_length=200)),
                ('bundle_type', models.CharField(choices=[('10_snacks', '10 Snacks'), ('25_snacks', '25 Snacks'), ('25_juices', '25 Juices'), ('mega_mix', 'Mega Mix'), ('custom', 'Custom')], max_length=20)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('payment_uploaded', 'Payment Uploaded'), ('payment_verified', 'Payment Verified'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin about order modifications')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/%d/')),
                ('payment_method', models.CharField(blank=True, help_text='e.g., Bank Transfer, NCB, etc.', max_length=50, null=True)),
                ('order_reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_starred', models.BooleanField(default=False, help_text='Customer wants more of this item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_order_items', to='core.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order_items', to='core.customerorder')),
            ],
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['status'], name='core_custom_status_476c75_idx'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['bundle_type'], name='core_custom_bundle__cb33a9_idx'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['created_at'], name='core_custom_created_1597b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerorderitem',
            unique_together={('order', 'item')},
        ),
    ]
