# Generated by Django 5.1.7 on 2026-01-22 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bankinginfo_customerorder_customerorderitem_and_more'),
    ]

    operations = [
        # payment_deadline column already exists, skip database operation
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='customerorder',
                    name='payment_deadline',
                    field=models.DateTimeField(blank=True, help_text='24-hour deadline for payment after approval', null=True),
                ),
            ],
        ),
        # PushSubscription table already exists, skip database operation
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='PushSubscription',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('endpoint', models.TextField(unique=True)),
                        ('keys', models.JSONField(help_text='Auth and p256dh keys')),
                        ('user_agent', models.CharField(blank=True, max_length=200)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'ordering': ['-created_at'],
                        'indexes': [models.Index(fields=['endpoint'], name='pushsubscription_endpoint_idx')],
                    },
                ),
            ],
        ),
        # CustomerSuggestion is new - create it
        migrations.CreateModel(
            name='CustomerSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('new_item', 'New Item Request'), ('feedback', 'General Feedback')], max_length=20)),
                ('item_name', models.CharField(blank=True, help_text='Name of item being suggested (for new_item type)', max_length=200)),
                ('message', models.TextField()),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('admin_response', models.TextField(blank=True, help_text="Admin's response to the suggestion")),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='core.customerorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['suggestion_type'], name='core_custom_suggest_cf92f0_idx'), models.Index(fields=['is_reviewed'], name='core_custom_is_revi_611876_idx'), models.Index(fields=['created_at'], name='core_custom_created_9cb93a_idx')],
            },
        ),
    ]
