# Generated by Django 5.1.7 on 2026-01-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customerorder_payment_deadline_pushsubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='payment_reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether payment reminder email has been sent'),
        ),
    ]
