# Generated by Django 5.1.7 on 2026-01-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_payment_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When admin confirmed payment', null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('ncb', 'NCB'), ('scotiabank', 'Scotiabank'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid'), ('pickup', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=20),
        ),
    ]
