"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Try to use PyMySQL as fallback if mysqlclient is not available
try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-change-this-in-production-!@#$%^&*()')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pwa',  # Progressive Web App support
    'core',  # Our main app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Use MySQL/MariaDB for GoDaddy database
# Set these in your .env file to connect to GoDaddy database
DB_NAME = os.getenv('DB_NAME', '')
DB_USER = os.getenv('DB_USER', '')
DB_PASSWORD = os.getenv('DB_PASSWORD', '')
DB_HOST = os.getenv('DB_HOST', 'localhost')
DB_PORT = os.getenv('DB_PORT', '3306')

# Always use MySQL if credentials are provided, otherwise use SQLite
if DB_NAME and DB_USER and DB_PASSWORD:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
            },
            # Connection timeout settings
            'CONN_MAX_AGE': 0,  # Don't persist connections (helps with connection issues)
        }
    }
    # Warn if using localhost (won't work for remote connections)
    if DB_HOST == 'localhost':
        import warnings
        warnings.warn(
            "DB_HOST is set to 'localhost'. This won't work for remote database connections. "
            "Update DB_HOST in your .env file with the actual GoDaddy database hostname.",
            UserWarning
        )
else:
    # SQLite for local development (only if no DB credentials provided)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation (moved to bottom for better organization)


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for static files
# Use CompressedStaticFilesStorage instead of Manifest to avoid missing file errors
# Run 'python manage.py collectstatic' after deployment
if DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security settings (apply in both dev and production)
SECURE_BROWSER_XSS_FILTER = True  # Enable browser XSS filter
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking
X_CONTENT_TYPE_OPTIONS = 'nosniff'  # Additional MIME type protection
REFERRER_POLICY = 'strict-origin-when-cross-origin'  # Control referrer information

# Additional security settings for production only
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year HSTS
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True  # HTTPS only cookies
    CSRF_COOKIE_SECURE = True  # HTTPS only CSRF cookies
    SECURE_SSL_REDIRECT = True  # Force HTTPS in production
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # For proxies/load balancers

# Session security
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True  # Extend session on activity
SESSION_COOKIE_AGE = 3600  # 1 hour session timeout
SESSION_COOKIE_NAME = 'jem_sessionid'  # Custom session cookie name

# CSRF security
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access for AJAX requests
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_FAILURE_VIEW = 'core.views.csrf_failure'  # Custom CSRF failure view
# CSRF_USE_SESSIONS = True  # Uncomment if cookie-based CSRF continues to fail

# CSRF Trusted Origins - required for Django 4.0+
# In development, allow localhost
# In production, use environment variable or default to your domain
if DEBUG:
    # Development: allow localhost and 127.0.0.1
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://localhost',
        'http://127.0.0.1',
    ]
else:
    # Production: get from environment or use default
    env_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '').strip()
    if env_origins:
        CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in env_origins.split(',') if origin.strip()]
    else:
        # Default trusted origins for GoDaddy production
        CSRF_TRUSTED_ORIGINS = [
            'https://jem.rixsoft.org',
            'https://www.jem.rixsoft.org',
        ]

# Password security
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Login URLs
LOGIN_URL = 'admin_login'
LOGIN_REDIRECT_URL = 'admin_dashboard'
LOGOUT_REDIRECT_URL = 'admin_login'

# PWA Configuration
PWA_APP_NAME = 'J.E.M - Just Eat More'
PWA_APP_DESCRIPTION = "Premium snack bundles for kids in Jamaica. Perfect for lunch boxes, after-school treats, and class parties."
PWA_APP_THEME_COLOR = '#2563EB'  # Blue color for status bar and navigation overlay
PWA_APP_BACKGROUND_COLOR = '#FFFFFF'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'portrait'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/favicons/icon-192.png',
        'sizes': '192x192',
        'type': 'image/png',
        'purpose': 'any'
    },
    {
        'src': '/static/favicons/icon-512.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'any'
    },
    {
        'src': '/static/favicons/icon-192.png',
        'sizes': '192x192',
        'type': 'image/png',
        'purpose': 'maskable'
    },
    {
        'src': '/static/favicons/icon-512.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'maskable'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/favicons/icon-512.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'
PWA_APP_SHORT_NAME = 'J.E.M'
PWA_APP_ID = 'com.jem.justeatmore'
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static', 'js', 'serviceworker.js')

# PWA Screenshots for app store (mobile portrait screenshots)
# Only include screenshots that actually exist in static/screenshots/
PWA_APP_SCREENSHOTS = [
    {
        'src': '/static/screenshots/Screenshot 2026-01-21 135800.png',
        'sizes': '466x839',
        'type': 'image/png',
        'form_factor': 'narrow'
    },
    {
        'src': '/static/screenshots/Screenshot 2026-01-21 135836.png',
        'sizes': '474x839',
        'type': 'image/png',
        'form_factor': 'narrow'
    },
    {
        'src': '/static/screenshots/Screenshot 2026-01-21 135922.png',
        'sizes': '469x843',
        'type': 'image/png',
        'form_factor': 'narrow'
    },
    {
        'src': '/static/screenshots/Screenshot 2026-01-21 135939.png',
        'sizes': '474x839',
        'type': 'image/png',
        'form_factor': 'narrow'
    },
    {
        'src': '/static/screenshots/Screenshot 2026-01-21 140006.png',
        'sizes': '467x836',
        'type': 'image/png',
        'form_factor': 'narrow'
    }
]

# PWA Offline support
PWA_APP_OFFLINE_URL = '/offline/'

# Push Notifications (VAPID Keys)
# Generate these keys using: python generate_vapid_keys.py
# Store these securely - never commit private key to version control
# For local development, keys are set below. For production, use environment variables.

# Resend Email Configuration
RESEND_API_KEY = os.getenv('RESEND_API_KEY', '')
ADMIN_EMAIL = 'justeatmore876@gmail.com'
# Use onboarding@resend.dev for testing if your domain isn't verified
FROM_EMAIL = os.getenv('FROM_EMAIL', 'onboarding@resend.dev') 
